version: '3.3'

services:
  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./storage/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

  # app:
  #   build: .
  #   image: go-boilerplate:latest
  #   depends_on:
  #     - mongo
  #     - redis
  #   volumes:
  #     - ./example.config.yaml:/etc/go-boilerplate/app.config.yaml
  #   ports:
  #     - 8080:8080
  #     - 3550:3550
  #   command: 'serve-grpc-rest --config /etc/go-boilerplate/app.config.yaml'
