version: '3.3'

services:
  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=mahfuz
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=epay_wallet
    ports:
      - 5432:5432
#  mongo:
#    image: mongo:3.6
#    restart: always
#    ports:
#      - 27017:27017
#    volumes:
#      - ./storage/mongo:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: secret

#   app:
#     build: .
#     image: go-boilerplate:latest
#     depends_on:
#       - postgresql
#       - redis
#     volumes:
#       - ./example.config.yaml:/etc/go-boilerplate/app.config.yaml
#     ports:
#       - 8080:8080
#       - 3550:3550
#     command: 'serve-grpc-rest --config /etc/go-boilerplate/app.config.yaml'
